# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0002_auto_20170726_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'creation_time'},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('content', 'parent')]),
        ),
    ]
