# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0003_auto_20170727_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='super_parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='super_children', to='storyboard.Post'),
            preserve_default=False,
        ),
    ]
