# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0004_post_super_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='super_parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_children', to='storyboard.Post'),
        ),
    ]
